---

# Set this value to non-empty value 
# to trace task shell execution
trace_tasks: 'Y'

# The underlying IAAS
iaas: 'gcp'

# GCP project
gcp_project_id: '${gcp_project}'

# GCP service account json
gcp_service_account_key: |
  ${gcp_credentials}

# IAAS instance tag to use for when 
# searching for instances in deployment
# to start or stop
label: $'{vpc_name}-pcf'

# The automation repository
automation_pipelines_url: '${automation_pipelines_url}'
automation_pipelines_branch: '${automation_pipelines_branch}'

# Pivotal Ops Manager host and credentials
opsman_host: 'opsman.pas.${vpc_dns_zone}'
opsman_user: 'admin'
opsman_passwd: '${opsman_admin_password}'
opsman_ssh_user: 'ubuntu'
opsman_ssh_passwd: ''
opsman_pass_phrase: '${opsman_admin_password}'
pcfops_client: ''
pcfops_secret: ''

# Locale to use for timer resources
locale: ${locale}

# Time period during which the stop 
# schedule will trigger a stop event
stop_trigger_start: ${pcf_stop_trigger_start}
stop_trigger_stop: ${pcf_stop_trigger_stop}
stop_trigger_days: ${pcf_stop_trigger_days}

# Time period during which the start 
# schedule will trigger a stop event
start_trigger_start: ${pcf_start_trigger_start}
start_trigger_stop: ${pcf_start_trigger_stop}
start_trigger_days: ${pcf_start_trigger_days}
